version: '3'

services:
  python_app:
    build:
        context: .
        dockerfile: Dockerfile.dev
    volumes:
        - ./:/app
    container_name: python_app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    tty: true
    stdin_open: true